#!/bin/bash

### BEGIN INIT INFO
# Provides:          jira
# Required-Start:    $remote_fs $syslog $time $named
# Required-Stop:     $remote_fs $syslog $time $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Atlassian Jira
# Description: Atlassian Jira Server
### END INIT INFO

# JIRA Linux service controller script
cd /opt/atlassian/jira/bin

case "$1" in
    start)
        ./start-jira.sh
        ;;
    stop)
        ./stop-jira.sh
        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac